on:
  push:
    branches:
      - master
      - release/*
      -

jobs:
  build:
    name: Check out code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.19.2
        name: get dependencies
      - run: flutter pub get
        name: build apk
      - run: flutter build apk --release --split-per-abi

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "Release"
          release_tag: "v1.0.0"
          release_body: "Release"
          draft: false
          prerelease: false

